apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rccremote-ingress
  namespace: rccremote
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - rccremote.local
    - "*.rccremote.local"
    secretName: rccremote-tls
  rules:
  - host: rccremote.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rccremote
            port:
              number: 443
